### ISSUE TITLE
Missing requirement pycryptodomex

### ISSUE THREAD

**Issue by goldenpipes** [rix1337/MyJD-API#3]
is this thing broken?

no module named cryptodome?

**Comment by rix1337** [comment]
No, this works fine.

**Comment by goldenpipes** [comment]
well idk what the hell im doing wrong, ive tried running this in your docker container, and just via pip install.

i just get this error every time.
```cmd
Traceback (most recent call last):
  File "c:\users\lewis\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\lewis\appdata\local\programs\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\lewis\AppData\Local\Programs\Python\Python36\Scripts\myjd_api.exe\__main__.py", line 5, in <module>
  File "c:\users\lewis\appdata\local\programs\python\python36\lib\site-packages\myjd_api\web.py", line 31, in <module>
    from myjd_api.common import check_ip
  File "c:\users\lewis\appdata\local\programs\python\python36\lib\site-packages\myjd_api\common.py", line 10, in <module>
    from myjd_api import myjdapi
  File "c:\users\lewis\appdata\local\programs\python\python36\lib\site-packages\myjd_api\myjdapi.py", line 42, in <module>
    from Cryptodome.Cipher import AES
ModuleNotFoundError: No module named 'Cryptodome'
```

**Comment by rix1337** [comment]
This seems to be a relevant issue, thanks for opening. Some required module seems to be wrongly included.

**Comment by rix1337** [comment]
Good find, will be fixed next version.

**Comment by rix1337** [comment]
Workaround for now: 
`pip install pycryptodomex`
